mybatis-plus:
#  type-enums-package:
#  mapper-locations:
  check-config-location: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.2.175:10000/pub-key/jwk.json
      client:
        registration:
          google:
            client-id: YOUR_APP_CLIENT_ID
            client-secret: YOUR_APP_CLIENT_SECRET

app:
  id-gen:
    worker-id: 0
    data-center-id: 0
  cors:
    path-pattern: /**
    allowed-origins:
      - "*"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed-headers:
      - Authorization
    exposed-headers:
    allow-credentials: true
    max-age: 3600
  security:
    login-url: /auth/login
    logout-url: /auth/logout
    matcher:
      permit-all:
        - /home
        - /exists/**
      authenticated:
        - /user/me